### ISSUE TITLE
[DOCS] Dependencies not installed for fedora

### ISSUE THREAD

**Issue by superbonaci** [CCExtractor/ccextractor#1596]
When trying to compile with fedora 39:
```
$ ./build
warning: unused doc comment
   --> src/decoder/window.rs:450:13
    |
450 |             /// Either N/A or black, still always 0
    |             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
451 |             edge_color: 0,
    |             ------------- rustdoc does not generate documentation for expression fields
    |
    = help: use `//` for a plain comment

warning: `ccx_rust` (lib) generated 3 warnings
    Finished release [optimized] target(s) in 1m 33s
Building ccextractor
Compiled with errors
../src/lib_ccx/mp4.c:5:10: fatal error: gpac/isomedia.h: No such file or directory
    5 | #include <gpac/isomedia.h>
      |          ^~~~~~~~~~~~~~~~~
compilation terminated.
../src/lib_ccx/params.c:4:10: fatal error: gpac/setup.h: No such file or directory
    4 | #include "gpac/setup.h"
      |          ^~~~~~~~~~~~~~
compilation terminated.
```

**Comment by superbonaci** [comment]
It's fixed by
```
$ sudo dnf install gpac-devel
```

Please add to https://github.com/CCExtractor/ccextractor/blob/master/docs/COMPILATION.MD

**Comment by anshravalll** [comment]
For anyone installing GPAC directly from source in the future, I recommend reaading the documentation available on the GPAC  repository. Specifically, ensure that you compile it using the gpac-devel option.

CCExtractor by default searches for the GPAC library's shared object file (.so) within the bin/lib directory of Linux distributions. if compiler still doesn't find GPAC lib than do the following:

    Directly compile GPAC into this bin/lib location.
    Create symbolic links in bin/lib that point to your compiled GPAC .so file.

This will help CCExtractor to find the necessary GPAC library files.
