### ISSUE TITLE
DVB-subtitle-track not discovered

### ISSUE THREAD

**Issue by hurda** [CCExtractor/ccextractor#247]
CCExtractor 0.77 and git-677fee4 
File: http://www.mediafire.com/download/lzruvndz9mzoxul/dvb_not_found.7z (26MB)

The dvb-stream isn't detected, while extracting the teletext-subtitles works.
With 0.77 the program produces an empty SRT-file.

```
C:\Users\User\Videos\cce>ccextractorwin.exe  --gui_mode_reports  -autoprogram -o
ut=srt -bom -debug -goppts -vides -parsePAT -parsePMT -deblev -utf8 -noteletext 
"dvb not found.ts"
###VERSION#CCExtractor#0.77
CCExtractor 0.77, Carlos Fernandez Sanz, Volker Quetschke.
Teletext portions taken from Petr Kutalek's telxcc
--------------------------------------------------------------------------
Input: dvb not found.ts
[Extract: 1] [Stream mode: Autodetect]
[Program : 0 ] [Hauppage mode: No] [Use MythTV code: Auto]

[Timing mode: Auto] [Debug: Yes] [Buffer input: Yes]
[Use pic_order_cnt_lsb for H.264: No] [Print CC decoder traces: No]
[Target format: .srt] [Encoding: UTF-8] [Delay: 0] [Trim lines: No]
[Add font color data: Yes] [Add font typesetting: Yes]
[Convert case: No] [Video-edit join: No]
[Extraction start time: not set (from start)]
[Extraction end time: not set (to end)]
[Live stream: No] [Clock frequency: 90000]
Teletext page: [Autodetect]
Start credits text: [None]
Creating dvb not found.srt

-----------------------------------------------------------------
Opening file: dvb not found.ts
###INPUTFILEOPEN#dvb not found.ts
File seems to be a transport stream, enabling TS mode
Analyzing data in general mode
Read PAT packet (id: 0) ts-id: 0x0002
  section length: 13  number: 0  last: 0
  version_number: 0  current_next_indicator: 1

Program association section (PAT)
  Program number: 2001  -> PMTPID: 2000

Program Map Table for program 2001, PMT PID: 2000
  2001 |   2 (  2) | MPEG-2 video
  2011 |   3 (  3) | MPEG-1 audio
  2101 |   6 (  6) | MPEG-2 private data
  2071 |   6 (  6) | MPEG-2 private data

---

Program map section (PMT)
  MPEG-2 video stream [0x02]  -  PID: 2001
  MPEG-1 audio stream [0x03]  -  PID: 2011
  MPEG-2 private data stream [0x06]  -  PID: 2101
  MPEG-2 private data stream [0x06]  -  PID: 2071

First sync time    PTS: 21:57:37:818 +0ms (time before this PTS)
Total_frames_count 0 frames_since_ref_time 0
Packet (pid 2071) skipped - no payload.
Packet (pid 2071) skipped - no payload.
TS payload start video PES id: 189  len: 2279
Set PTS: 21:57:41:752 (2820590394)
PES header length: 14 (14 verified)  Data length: 2265
Read PES-DVB subtitle (databuffer 2265/PES data 2265)  - complete
###PROGRESS#6#0#3
Packet (pid 2071) skipped - no payload.
Packet (pid 2071) skipped - no payload.
Packet (pid 2071) skipped - no payload.
TS payload start video PES id: 189  len: 5067
Set PTS: 21:57:43:392 (2820737994)
PES header length: 14 (14 verified)  Data length: 5053
Read PES-DVB subtitle (databuffer 5053/PES data 5053)  - complete
###PROGRESS#10#0#5


[etc. etc. etc.]


Number of NAL_type_7: 0
Number of VCL_HRD: 0
Number of NAL HRD: 0
Number of jump-in-frames: 0
Number of num_unexpected_sei_length: 0

Total frames time:        00:00:00:000  (0 frames at 29.97fps)

Min PTS:                                21:57:37:818
Max PTS:                                21:58:34:152
Length:                          00:00:56:334
Done, processing time = 2 seconds
Performance (real length/process time) = 28.18
This is beta software. Report issues to carlos at ccextractor org...
```

But with the compiled git-version, the program crashes at the OCR-stage:

```
\src\lib_ccx\ocr.c
Line: 134

Run-Time Check Failure #3 - The variable 'end_y' is being used without being initialized.
```

**Comment by cfsmp3** [comment]
Just tested - the crash with OCR is still there today. Assigned to Abhinav95 since he's doing DVB work these days.

Abhinav95 I can reproduce by doing this:

-codec dvbsub -stdout -srt "C:\DeletableTempStuff\dvb not found.ts"

0.82 to be released once this is fixed.

**Comment by grave-w-grave** [comment]
Resolved as of 0.82

**Comment by cfsmp3** [comment]
Can you send complete console output and also attach the resulting output
file to the ticket?

**Comment by grave-w-grave** [comment]
```
----------
Opening file: dvb not found.ts
File seems to be a transport stream, enabling TS mode
Analyzing data in general mode
VBI/teletext stream ID 2101 (0x835) for SID 2001 (0x7d1)
DVB subtitles detected, OCR subsystem not present. Use -out=spupng for graphic output
Creating dvb not found.srt
  0%  |  00:00- Programme Identification Data = ARD - Das Erste.
- Universal Time Co-ordinated = Thu Nov 05 03:48:52 2015
Notice: Teletext page with possible subtitles detected: 150
- No teletext page specified, first received suitable page is 150, not guaranteed
100%  |  00:55
Teletext decoder: 1390 packets processed

Number of NAL_type_7: 0
Number of VCL_HRD: 0
Number of NAL HRD: 0
Number of jump-in-frames: 0
Number of num_unexpected_sei_length: 0
Done, processing time = 0 seconds
This is beta software. Report issues to carlos at ccextractor org...
```


[dvb not found.zip](https://github.com/CCExtractor/ccextractor/files/617788/dvb.not.found.zip)

**Comment by hurda** [comment]
Doesn't work for me in 0.85:
`C:\Temp\downloads\ccextractor.0.85-windows.binaries\ccextractorwinfull.exe  --gui_mode_reports  -autoprogram  -out=srt -bom -latin1 -codec dvbsub [+input files]`

```
CCExtractor 0.85, Carlos Fernandez Sanz, Volker Quetschke.
Teletext portions taken from Petr Kutalek's telxcc
--------------------------------------------------------------------------
Input: C:\Users\hurda\Videos\dvb not found.ts
[Extract: 1] [Stream mode: Autodetect]
[Program : Auto ] [Hauppage mode: No] [Use MythTV code: Auto]
[Timing mode: Auto] [Debug: No] [Buffer input: Yes]
[Use pic_order_cnt_lsb for H.264: No] [Print CC decoder traces: No]
[Target format: .srt] [Encoding: Latin-1] [Delay: 0] [Trim lines: No]
[Add font color data: Yes] [Add font typesetting: Yes]
[Convert case: No] [Video-edit join: No]
[Extraction start time: not set (from start)]
[Extraction end time: not set (to end)]
[Live stream: No] [Clock frequency: 90000]
[Teletext page: Autodetect]
[Start credits text: None]


-----------------------------------------------------------------

Opening file: C:\Users\hurda\Videos\dvb not found.ts

File seems to be a transport stream, enabling TS mode

Analyzing data in general mode
Creating C:\Users\hurda\Videos\dvb not found.srt
dvbsub_decode: incomplete, broken or empty packet

Number of NAL_type_7: 0
Number of VCL_HRD: 0
Number of NAL HRD: 0
Number of jump-in-frames: 0
Number of num_unexpected_sei_length: 0

Min PTS:				21:57:37:818
Max PTS:				21:58:34:152
Length:				 00:00:56:334

Done, processing time = 2 seconds
Issues? Open a ticket here
https://github.com/CCExtractor/ccextractor/issues
No captions were found in input.
```

Plus the log of @grave-w-grave shows it was extracting the Teletext-subtitles, not the DVB-subtitles, which weren't an issue.

**Comment by cfsmp3** [comment]
Confirmed - it still crashes. I looked into it and the first crash is caused due to uninitialized variables.

Trivial "fix":
BOX* ignore_alpha_at_edge(png_byte *alpha, unsigned char* indata, int w, int h, PIX *in, PIX **out)
{
	int i, j, index, start_y, end_y;
	int i, j, index, start_y=0, end_y=0;

But we don't get much further than that - eventually tesseract returns an 0 which we don't really handle well (we write "something messy" and go on with our day) and then another crash.

@Abhinav95 can you check this out?

**Comment by gray-v** [comment]
Tesseract thingy fixed, but this still crashes at PTS: 21:57:43:392 (2820737994)  FTS: 00:00:05:280 due to access violation, trying to read from a pointer to 0 at some point
